name: rubecube
version: "1.0"
summary: An interactive Rubik's Cube simulation in 3D.
description: Play with a virtual Rubik's Cube through an intuitive interface.
  Simulate Rubik's Cubes of various dimensions.  Watch the computer scramble and solve them.
  Save and load cubes to/from disk.  Create and test your own algorithms.
  Move backwards and forward through your own rotation history.
  Customize your cube by changing the face textures.  Apply your own bandaging to the cube.
confinement: strict

apps:
  rubecube:
    command: env UBUNTU_MENUPROXY=0 desktop-launch $SNAP/bin/RubeCube
    plugs: [home, x11, unity7, process-control]

parts:
  rubecube:
    plugin: scons
    source: https://github.com/spencerparkin/RubiksCube.git
    source-branch: stable-release
    after: [desktop-gtk2]

